# Generated by Django 5.0 on 2023-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_image',
            name='id_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
