# Generated by Django 5.0 on 2023-12-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_id_image_id_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_image',
            name='id_img',
        ),
    ]
