# Generated by Django 5.0 on 2023-12-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_id_image_id_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_image',
            name='id_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
