# Generated by Django 5.0 on 2023-12-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_card',
            name='id_card_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.id_image'),
        ),
    ]
