# Generated by Django 5.0 on 2023-12-24 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_id_card_id_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_card',
            name='id_card_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.id_image'),
        ),
    ]
